### PR TITLE
updatedhtml

### PR DESCRIPTION
**Pull request by juliana102**
Added background image, added button, adjusted button sizes

### CODE REVIEW

**Review by eigueso — CHANGES_REQUESTED** [review]
Did you mean to add this as a mock html on its own or you’d like to merge the whole front end branch with this file included?

**Comment by juliana102** [comment]
I meant to add it as a mock html

**Comment by eigueso** [comment]
Cool, it went in as if you wanted to merge it as a whole. If you’d like, I can separate it and create a new branch called Juliana/html-update and add the updated HTML there. Or just add it to the previous Juliana/html branch as an override of the previous file or in addition to the old one, your choice.

**Comment by juliana102** [comment]
Oh yea we can just do an override of my previous branch.

**Comment by eigueso** [comment]
Ok, done.

**Comment by juliana102** [comment]
Thank you!!

**Pull request closed without merging**
